name: Java CI with Maven
permissions: write-all
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package
      
    - name: Set up GitHub Packages
      run: |
        echo "//maven.pkg.github.com/${{ github.repository }}" > ~/.m2/settings.xml
        echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" >> ~/.m2/settings.xml
        
    - name: Publish to GitHub Packages
      run: mvn deploy
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
